#!/usr/bin/env python3
"""Pre-Entry Validation Filter — THE GATE before any trade is taken.

Integrates:
1. Reversal detection (reversal_detector.py)
2. MiroFish contrarian signal checking
3. Confluence minimum (≥3 required)
4. Volume/momentum health
5. Risk agent validation (R:R, symbol safety, cooldown)

Usage:
    python3 entry_filter.py \
      --symbol XAUUSD --direction LONG \
      --entry 4775 --sl 4750 --tp1 4820 --tp2 4840 \
      --mirofish-result ~/hermes/trades/2026-04-10/mirofish/validation_xau_lon.json \
      --confluences 4

Exit codes:
    0 = APPROVED — trade passes all gates
    1 = REJECTED — trade fails one or more gates
    2 = WARNING — trade passes but with notable risks
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from reversal_detector import ReversalDetector
from regime_filter import classify_regime


# === THRESHOLDS ===
MIN_CONFLUENCES = 3          # Minimum independent validations per setup
MIN_RR_RATIO = 2.0           # Minimum risk:reward ratio
MAX_CONSECUTIVE_LOSSES = 2   # After this many losses, extra scrutiny
REVERSAL_RISK_BLOCK = "CRITICAL"  # Block trades at this reversal risk level
VOLUME_EXHAUSTION_PENALTY = 0.5   # Score penalty for volume exhaustion

# === WEEKLY EXHAUSTION CHECK ===
# Block entries chasing moves that already ran X% in the past week
WEEKLY_MOVE_BLOCK_PCT = {
    "XAUUSD": 4.0,   # Gold: >4% weekly = chasing (tightened from 5.0)
    "XAGUSD": 5.0,   # Silver: >5% weekly = chasing (tightened from 7.0)
    "USOIL": 5.0,    # Oil: >5% weekly = chasing (tightened from 6.0)
    "DEFAULT": 3.0,  # Other pairs: >3% weekly = chasing (tightened from 4.0)
}

# === MAX SL DISTANCE CHECK ===
# SL should never be wider than this without ATR justification
MAX_SL_DISTANCE = {
    "XAUUSD": 150.0,   # Gold: max 150 points ($150/oz)
    "XAGUSD": 2.0,     # Silver: max 2.0 points ($2/oz) — tightened
    "USOIL": 3.0,      # Oil: max $3
    "DEFAULT": 80,     # Other: 80 pips
}

# === MAX SL vs ATR ===
# SL distance should never exceed ATR * this multiplier
SL_ATR_MULTIPLIER = 2.5  # SL can be at most 2.5x ATR distance

# === $5 MAX RISK ===
MAX_DOLLAR_RISK = 5.0  # Ryan's hard limit per trade

# === WEEKEND HOLD RISK ===
# Friday after 18:00 UTC = elevated weekend gap risk
WEEKEND_HOLD_RR_MULTIPLIER = 1.5  # R:R must be 1.5x higher for Friday holds
WEEKEND_HOLD_DAY = 4              # Friday = 4 (Mon=0)
WEEKEND_HOLD_HOUR_UTC = 18        # After 18:00 UTC Friday

# === MAX RISK PER SYMBOL ===
# Per-symbol cooldown: block re-entry on same pair after loss for N hours
SYMBOL_COOLDOWN_HOURS = 4

# === ADAPTIVE SESSION QUALITY ===
# Path to session quality data generated by session_quality_tracker.py
SESSION_QUALITY_PATH = Path.home() / "vibe-trading" / "state" / "session_quality.json"
# Path to trade journal for symbol cooldown lookup
JOURNAL_PATH = Path.home() / ".hermes" / "vibe-trading" / "trade_journal.json"


def load_adaptive_session_quality() -> dict:
    """Load session quality stats computed from actual trade outcomes.

    Returns dict mapping session name → {action, score_penalty, recommendation, win_rate}.
    Empty dict if file doesn't exist (system degrades gracefully to static tiers).
    """
    if not SESSION_QUALITY_PATH.exists():
        return {}
    try:
        with open(SESSION_QUALITY_PATH) as f:
            data = json.load(f)
        return data.get("sessions", {})
    except (json.JSONDecodeError, IOError):
        return {}


def detect_session() -> str:
    """Auto-detect the current trading session based on UTC time.

    Returns session name for quality assessment in entry_filter.
    Based on major forex session hours:
      London:  07:00-16:00 UTC
      NY:      12:00-22:00 UTC (overlap with London 12:00-16:00)
      Asian:   00:00-07:00 UTC
    """
    hour = datetime.now(timezone.utc).hour

    if 0 <= hour < 7:
        return "asian"
    elif 7 <= hour < 12:
        return "london"
    elif 12 <= hour < 16:
        return "ny_overlap"
    elif 16 <= hour < 18:
        return "ny_morning"
    elif 18 <= hour < 22:
        return "ny_close"
    else:  # 22-24
        return "pre_asian"


class EntryFilter:
    """Pre-entry gate — checks EVERYTHING before a trade can be taken."""

    def __init__(self):
        self.reversal_detector = ReversalDetector()
        self.results = []
        self.score = 10.0  # Start at 10, deduct for issues
        self.blocked = False
        self.block_reasons = []
        self.warnings = []

    def check_risk_reward(self, entry: float, sl: float, tp1: float) -> dict:
        """Check R:R ratio — hard block if below minimum."""
        risk = abs(entry - sl)
        reward = abs(tp1 - entry)

        if risk <= 0:
            self.blocked = True
            self.block_reasons.append("Zero risk distance — invalid setup")
            return {"passed": False, "rr": 0, "reason": "Zero risk"}

        rr = round(reward / risk, 2)
        result = {"passed": rr >= MIN_RR_RATIO, "rr": rr}

        if not result["passed"]:
            self.blocked = True
            reason = f"R:R {rr}:1 below minimum {MIN_RR_RATIO}:1"
            self.block_reasons.append(reason)
            result["reason"] = reason
            self.score -= 10  # Fatal
        else:
            result["reason"] = f"R:R {rr}:1 — OK"

        return result

    def check_confluences(self, count: int) -> dict:
        """Check minimum confluence count."""
        result = {"passed": count >= MIN_CONFLUENCES, "count": count}

        if not result["passed"]:
            self.blocked = True
            reason = f"Only {count} confluences — minimum {MIN_CONFLUENCES} required"
            self.block_reasons.append(reason)
            result["reason"] = reason
            self.score -= 10  # Fatal
        else:
            result["reason"] = f"{count} confluences — OK"

        return result

    def check_mirofish_contraind(self, mirofish_result: dict) -> dict:
        """Check MiroFish validation result for contrarian blocks and warnings."""
        consensus = str(mirofish_result.get("consensus", "")).upper()
        result = {"passed": True, "consensus": consensus, "signals": []}

        # Hard blocks
        if consensus in ("REJECTED", "CONTRARIAN_BLOCK", "RR_BLOCKED", "UNCERTAIN"):
            result["passed"] = False
            reason = f"MiroFish consensus: {consensus}"
            result["signals"].append(reason)
            self.blocked = True
            self.block_reasons.append(reason)
            self.score -= 10
            return result

        # Check for contrarian agent warnings in agent data
        agent_data = mirofish_result.get("agents", {})
        if isinstance(agent_data, list):
            agents_list = agent_data
        elif isinstance(agent_data, dict):
            agents_list = list(agent_data.values())
        else:
            agents_list = []

        # Handle both dict and list formats for agent iteration
        if isinstance(agent_data, dict):
            agent_pairs = list(agent_data.items())
        elif isinstance(agent_data, list):
            agent_pairs = [(a.get("agent", a.get("name", "")), a) for a in agent_data if isinstance(a, dict)]
        else:
            agent_pairs = []

        for agent_key, agent_info in agent_pairs:
            if not isinstance(agent_info, dict):
                continue
            agent_name = str(agent_info.get("agent", agent_info.get("name", agent_key))).upper()
            vote = str(agent_info.get("vote", "")).upper()
            score_val = agent_info.get("score", agent_info.get("confidence", 0))
            try:
                score_f = float(score_val)
            except (ValueError, TypeError):
                score_f = 0

            if "CONTRARIAN" in agent_name:
                # Check for strong contrarian opposition
                opposition_keywords = {"NO", "DISAGREE", "REJECT", "OPPOSE", "INVALID", "BEARISH", "SHORT", "SELL"}
                warning_keywords = {"CAUT", "NEUTRAL", "UNCERTAIN", "WAIT", "RISKY", "WARNING", "MONITOR", "WATCH"}
                reversal_keywords = {"HAMMER", "SHOOTING_STAR", "ENGULFING", "EVENING_STAR", "MORNING_STAR", "DARK_CLOUD", "HANGING_MAN"}

                if any(kw in vote for kw in opposition_keywords):
                    reason = f"CONTRARIAN_AGENT opposes: '{vote}' (score: {score_f})"
                    result["signals"].append(reason)
                    if score_f > 5:
                        self.blocked = True
                        self.block_reasons.append(reason)
                        result["passed"] = False
                        self.score -= 10
                    else:
                        self.warnings.append(reason)
                        self.score -= 3

                elif any(kw in vote for kw in warning_keywords):
                    reason = f"CONTRARIAN_AGENT warns: '{vote}' (score: {score_f})"
                    result["signals"].append(reason)
                    if score_f > 6:
                        self.blocked = True
                        self.block_reasons.append(f"Contrarian caution with score {score_f} > 6 — HARD BLOCK")
                        result["passed"] = False
                        self.score -= 10
                    else:
                        self.warnings.append(reason)
                        self.score -= 2

                # Check rationale for reversal pattern keywords
                rationale = str(agent_info.get("rationale", agent_info.get("reason", ""))).upper()
                if any(kw in rationale for kw in reversal_keywords):
                    reason = f"CONTRARIAN_AGENT flags reversal pattern in rationale"
                    result["signals"].append(reason)
                    self.warnings.append(reason)
                    self.score -= 2

        # Check top-level vote for contrarian signals
        top_vote = str(mirofish_result.get("vote", mirofish_result.get("final_vote", ""))).upper()
        top_score_raw = mirofish_result.get("score",
            mirofish_result.get("final_score",
            mirofish_result.get("confidence_score",
            mirofish_result.get("confidence", 0))))
        try:
            top_score = float(top_score_raw)
            if top_score > 100: top_score /= 10
            elif top_score > 10: top_score /= 10
            elif 0 < top_score <= 1: top_score *= 10
        except (ValueError, TypeError):
            top_score = 0

        risky_votes = {"RISKY", "WARNING", "DANGER", "CAUTION", "UNSURE"}
        if any(kw in top_vote for kw in risky_votes) and top_score > 5:
            reason = f"Top-level MiroFish vote: '{top_vote}' (score: {top_score:.0f}) — risky setup"
            result["signals"].append(reason)
            self.warnings.append(reason)
            self.score -= 2

        return result

    def check_reversal_risk(self, direction: str, rsi_data: dict = None,
                           volume_data: dict = None, candle_type: str = None) -> dict:
        """Run reversal detector and block if CRITICAL risk."""
        reversal_result = self.reversal_detector.analyze(
            direction=direction,
            rsi_data=rsi_data,
            volume_data=volume_data,
            candle_type=candle_type
        )

        risk_level = reversal_result.get("reversal_risk", "LOW")
        signals = reversal_result.get("signals", [])
        result = {"passed": True, "risk_level": risk_level, "signals": signals}

        if risk_level == "CRITICAL":
            self.blocked = True
            reason = f"Reversal risk CRITICAL — {len(signals)} signals detected"
            self.block_reasons.append(reason)
            result["passed"] = False
            result["reason"] = reason
            self.score -= 10
        elif risk_level == "HIGH":
            reason = f"Reversal risk HIGH — {len(signals)} signals, consider tightening stop"
            self.warnings.append(reason)
            result["reason"] = reason
            self.score -= 3
        elif risk_level == "MEDIUM":
            reason = f"Reversal risk MEDIUM — single signal detected"
            self.warnings.append(reason)
            result["reason"] = reason
            self.score -= 1

        # Volume exhaustion penalty
        vol_result = reversal_result.get("volume_exhaustion", {})
        if vol_result.get("detected"):
            self.score -= VOLUME_EXHAUSTION_PENALTY

        return result

    def check_session_timing(self, session: str = None) -> dict:
        """Check if we're in a valid trading session.

        AUTO-DETECTS session from UTC time if not explicitly provided.
        BLOCKS trades during low-quality sessions (NY close, pre-Asian gap).

        Uses DYNAMIC session quality from actual trade outcomes when available.
        Falls back to static tiers when no historical data exists.

        Static tier fallback:
          HIGH   = London (07:00-12:00 UTC), NY overlap (12:00-16:00 UTC)
          MEDIUM = Asian (00:00-07:00 UTC), NY morning (16:00-18:00 UTC)
          LOW    = NY close (18:00-22:00 UTC) → HARD BLOCK
          DEAD   = Pre-Asian gap (22:00-00:00 UTC) → HARD BLOCK
        """
        # Auto-detect session from UTC time if not provided
        if not session:
            session = detect_session()
            if session == "unknown":
                return {"passed": True, "reason": "Could not detect session — skipping"}

        session_lower = session.lower().replace("_", "").replace(" ", "")

        # === ADAPTIVE QUALITY: Use real trade outcomes when available ===
        adaptive = load_adaptive_session_quality()
        normalized_session = session_lower
        if session_lower in ("ny", "newyork"):
            now_utc = datetime.now(timezone.utc).hour
            if 12 <= now_utc < 16:
                normalized_session = "nyoverlap"
            elif 16 <= now_utc < 18:
                normalized_session = "nymorning"
            elif 18 <= now_utc < 22:
                normalized_session = "nyclose"
            else:
                normalized_session = "ny"

        # Try to match adaptive data (exact session name or normalized)
        adaptive_match = adaptive.get(session, adaptive.get(normalized_session))

        if adaptive_match and adaptive_match.get("has_enough_data"):
            # Use data-driven quality assessment
            action = adaptive_match.get("action", "none")
            win_rate = adaptive_match.get("win_rate", 0.5)
            rec = adaptive_match.get("recommendation", "OK")
            penalty = adaptive_match.get("score_penalty", 0)

            if action == "hard_block":
                reason = (f"Session: {session} — ADAPTIVE BLOCK. "
                         f"Historical WR: {win_rate*100:.0f}% ({adaptive_match['trades']} trades). "
                         f"Data says: {rec}. No entries in this session.")
                self.blocked = True
                self.block_reasons.append(reason)
                self.score -= 10
                return {"passed": False, "reason": reason, "quality": "ADAPTIVE_LOW",
                        "win_rate": win_rate, "source": "adaptive"}

            elif action == "score_penalty":
                reason = (f"Session: {session} — ADAPTIVE CAUTION. "
                         f"Historical WR: {win_rate*100:.0f}% ({adaptive_match['trades']} trades). "
                         f"Score penalty: -{penalty}.")
                self.warnings.append(reason)
                self.score -= penalty
                return {"passed": True, "reason": reason, "quality": "ADAPTIVE_MEDIUM",
                        "win_rate": win_rate, "source": "adaptive"}

            else:
                # Session is OK per adaptive data
                reason = f"Session: {session} — ADAPTIVE OK. Historical WR: {win_rate*100:.0f}%."
                return {"passed": True, "reason": reason, "quality": "ADAPTIVE_HIGH",
                        "win_rate": win_rate, "source": "adaptive"}

        # === FALLBACK: Static quality tiers (when no adaptive data) ===
        high_quality = {"london", "nyoverlap", "overlap"}
        medium_quality = {"asian", "nymorning", "nysession", "ny"}
        low_quality = {"nyclose", "late", "preasian", "dead"}

        if normalized_session in high_quality or session_lower in high_quality:
            result = {"passed": True, "reason": f"Session: {session} — HIGH quality", "quality": "HIGH", "source": "static"}
        elif normalized_session in medium_quality or session_lower in medium_quality:
            reason = f"Session: {session} — MEDIUM quality (reduced conviction)"
            self.warnings.append(reason)
            self.score -= 1
            result = {"passed": True, "reason": reason, "quality": "MEDIUM", "source": "static"}
        elif normalized_session in low_quality or session_lower in low_quality:
            reason = (f"Session: {session} — LOW quality. Late NY / pre-Asian sessions have "
                     f"low liquidity, wider spreads, and higher reversal risk. "
                     f"Historical data: 0% WR in this session. HARD BLOCK.")
            self.blocked = True
            self.block_reasons.append(reason)
            self.score -= 10
            result = {"passed": False, "reason": reason, "quality": "LOW", "source": "static"}
        else:
            # Unknown session — warn but allow
            reason = f"Session: {session} — unrecognized, treating as MEDIUM"
            self.warnings.append(reason)
            self.score -= 1
            result = {"passed": True, "reason": reason, "quality": "UNKNOWN", "source": "static"}

        return result

    def check_weekly_exhaustion(self, symbol: str, direction: str,
                                 week_open: float, current_price: float) -> dict:
        """Block entries chasing moves that already ran X% in the past week.

        If LONG and price already up >threshold% this week → buying the top → BLOCK.
        If SHORT and price already down >threshold% this week → chasing the bottom → BLOCK.
        """
        if week_open <= 0:
            return {"passed": True, "reason": "No weekly data — skipping exhaustion check"}

        # Sanity check: week_open must be within 20% of current price
        # (prevents cross-symbol contamination when wrong week_open is passed)
        price_ratio = current_price / week_open if week_open > 0 else 1
        if price_ratio < 0.8 or price_ratio > 1.2:
            return {"passed": True,
                    "reason": f"Week open {week_open} incompatible with price {current_price} — skipping exhaustion check"}

        weekly_pct = ((current_price - week_open) / week_open) * 100

        # Get threshold for this symbol
        threshold = WEEKLY_MOVE_BLOCK_PCT.get(symbol.upper(),
                     WEEKLY_MOVE_BLOCK_PCT["DEFAULT"])

        # For LONG: positive weekly move > threshold = chasing top
        # For SHORT: negative weekly move > threshold = chasing bottom
        chasing = False
        if direction == "LONG" and weekly_pct > threshold:
            chasing = True
            reason = f"WEEKLY EXHAUSTION: {symbol} already up {weekly_pct:.1f}% this week (>{threshold}%). Chasing the top."
        elif direction == "SHORT" and weekly_pct < -threshold:
            chasing = True
            reason = f"WEEKLY EXHAUSTION: {symbol} already down {abs(weekly_pct):.1f}% this week (>{threshold}%). Chasing the bottom."

        result = {"passed": True, "weekly_pct": round(weekly_pct, 2), "threshold": threshold}

        if chasing:
            self.blocked = True
            self.block_reasons.append(reason)
            result["passed"] = False
            result["reason"] = reason
            self.score -= 10  # Fatal
        else:
            result["reason"] = f"Weekly move {weekly_pct:+.1f}% — within bounds (±{threshold}%)"

        return result

    def check_weekend_hold_risk(self) -> dict:
        """Elevated R:R requirement for trades held over weekend.

        Friday after 18:00 UTC = weekend gap risk. Silver gapped 3% on this trade.
        HARD BLOCK if R:R < 3.0:1 on Friday evening.
        """
        now = datetime.now(timezone.utc)
        is_friday = now.weekday() == WEEKEND_HOLD_DAY
        is_late = now.hour >= WEEKEND_HOLD_HOUR_UTC

        result = {"passed": True, "is_weekend_hold": False}

        if is_friday and is_late:
            result["is_weekend_hold"] = True
            effective_min_rr = MIN_RR_RATIO * WEEKEND_HOLD_RR_MULTIPLIER
            reason = (f"WEEKEND HOLD RISK: Friday {now.hour}:00 UTC. "
                     f"R:R must be ≥{effective_min_rr}:1 (normal {MIN_RR_RATIO}:1) "
                     f"or close before market close.")
            # HARD BLOCK — no more weekend gap kills
            self.blocked = True
            self.block_reasons.append(reason)
            result["passed"] = False
            result["reason"] = reason
            result["effective_min_rr"] = effective_min_rr
            self.score -= 10
        else:
            result["reason"] = f"Day {now.strftime('%A')} {now.hour}:00 UTC — no weekend hold risk"

        return result

    def check_max_sl_distance(self, symbol: str, entry: float, sl: float,
                               atr: float = None) -> dict:
        """Block trades with absurdly wide stop losses.

        Two checks:
        1. Absolute max: SL distance must be within per-symbol limits
        2. ATR-relative: SL distance must be <= ATR * 2.5
        """
        sl_distance = abs(entry - sl)
        result = {"passed": True, "sl_distance": round(sl_distance, 4)}

        # Check 1: Absolute max
        max_sl = MAX_SL_DISTANCE.get(symbol.upper(), MAX_SL_DISTANCE["DEFAULT"])
        if sl_distance > max_sl:
            reason = f"SL DISTANCE {sl_distance:.4f} > max {max_sl} for {symbol}. Stop too wide."
            self.blocked = True
            self.block_reasons.append(reason)
            result["passed"] = False
            result["reason"] = reason
            self.score -= 10
            return result

        # Check 2: ATR-relative (if ATR provided)
        if atr and atr > 0:
            atr_max = atr * SL_ATR_MULTIPLIER
            if sl_distance > atr_max:
                reason = (f"SL DISTANCE {sl_distance:.4f} > ATR×{SL_ATR_MULTIPLIER} = {atr_max:.4f}. "
                         f"Stop is {sl_distance/atr:.1f}x ATR — too wide, reduce position or tighten SL.")
                self.blocked = True
                self.block_reasons.append(reason)
                result["passed"] = False
                result["reason"] = reason
                self.score -= 10
                return result

        result["reason"] = f"SL distance {sl_distance:.4f} — within limits"
        return result

    def check_regime(self, symbol: str, price: float,
                     high_52w: float = None, low_52w: float = None,
                     atr: float = None) -> dict:
        """Check market regime — block trades in capitulation or extreme volatility.

        Integrates regime_filter.py (price structure + ATR volatility dual approach).
        CAPITULATION or combined AVOID = hard block.
        CAUTION = score penalty + warning.
        """
        regime_data = classify_regime(price, high_52w, low_52w, atr)
        action = regime_data.get("action", "TRADE")
        regime_name = regime_data.get("regime", "UNKNOWN")
        multiplier = regime_data.get("risk_multiplier", 1.0)
        result = {"passed": True, "regime": regime_name, "action": action,
                  "multiplier": multiplier, "details": regime_data}

        if action == "SKIP" or multiplier <= 0:
            self.blocked = True
            reason = f"Regime: {regime_name} — SKIP (multiplier {multiplier}x). {regime_data.get('recommendation', '')}"
            self.block_reasons.append(reason)
            result["passed"] = False
            result["reason"] = reason
            self.score -= 10
        elif action == "AVOID":
            self.blocked = True
            reason = f"Regime: {regime_name} — AVOID. {regime_data.get('recommendation', '')}"
            self.block_reasons.append(reason)
            result["passed"] = False
            result["reason"] = reason
            self.score -= 10
        elif action == "CAUTION":
            reason = f"Regime: {regime_name} — CAUTION ({multiplier}x size). {regime_data.get('recommendation', '')}"
            self.warnings.append(reason)
            result["reason"] = reason
            self.score -= 2

        return result

    def check_consecutive_losses(self, max_streak: int = None) -> dict:
        """Circuit breaker: block new trades after N consecutive losses.

        Reads the trade journal to find the most recent consecutive loss streak
        across ALL symbols. After max_streak consecutive losses, trading is paused
        until a win resets the counter.

        This prevents compounding losses during unfavorable market conditions
        or when the scan logic has a systematic bias.
        """
        if max_streak is None:
            max_streak = MAX_CONSECUTIVE_LOSSES

        if not JOURNAL_PATH.exists():
            return {"passed": True, "reason": "No journal — skipping loss streak check"}

        try:
            with open(JOURNAL_PATH) as f:
                journal = json.load(f)
        except (json.JSONDecodeError, IOError):
            return {"passed": True, "reason": "Journal read error — skipping"}

        trades = journal.get("trades", [])
        closed = [t for t in trades if t.get("status") == "CLOSED"]

        if not closed:
            return {"passed": True, "reason": "No closed trades — skipping"}

        # Count consecutive losses from most recent trade backwards
        streak = 0
        streak_trades = []
        for t in reversed(closed):
            pnl = t.get("pnl", 0)
            if pnl < 0:
                streak += 1
                streak_trades.append({
                    "symbol": t.get("symbol", "?"),
                    "pnl": pnl,
                    "date": t.get("date", ""),
                    "session": t.get("note", "")[:60]
                })
            elif pnl > 0:
                break  # Win breaks the streak
            # pnl == 0 (scratch) — don't count but don't break streak either

        result = {"passed": True, "streak": streak, "max_allowed": max_streak}

        if streak >= max_streak:
            total_loss = sum(t["pnl"] for t in streak_trades)
            symbols_hit = set(t["symbol"] for t in streak_trades)
            reason = (f"LOSS STREAK CIRCUIT BREAKER: {streak} consecutive losses "
                     f"(max {max_streak}). Total: ${total_loss:.2f}. "
                     f"Symbols: {', '.join(symbols_hit)}. "
                     f"Trading paused until a win resets the counter.")
            self.blocked = True
            self.block_reasons.append(reason)
            result["passed"] = False
            result["reason"] = reason
            result["streak_details"] = streak_trades
            self.score -= 10  # Fatal
        elif streak == max_streak - 1:
            # One loss away from circuit breaker — extra warning
            reason = (f"⚠️ LOSS STREAK WARNING: {streak} consecutive losses. "
                     f"One more loss triggers circuit breaker (max {max_streak}). "
                     f"Only highest-conviction setups allowed.")
            self.warnings.append(reason)
            self.score -= 3  # Heavy penalty but not a block
            result["reason"] = reason
        else:
            result["reason"] = f"Loss streak: {streak}/{max_streak} — OK"

        return result

    def check_symbol_cooldown(self, symbol: str) -> dict:
        """Block re-entry on the same pair after a loss for SYMBOL_COOLDOWN_HOURS.

        Reads the trade journal to find the most recent closed loss for this symbol.
        Prevents revenge trading on pairs that just lost.
        """
        if not JOURNAL_PATH.exists():
            return {"passed": True, "reason": "No journal — skipping symbol cooldown"}

        try:
            with open(JOURNAL_PATH) as f:
                journal = json.load(f)
        except (json.JSONDecodeError, IOError):
            return {"passed": True, "reason": "Journal read error — skipping"}

        trades = journal.get("trades", [])
        now = datetime.now(timezone.utc)

        # Find most recent CLOSED loss on this symbol
        for t in reversed(trades):
            if t.get("symbol", "").upper() != symbol.upper():
                continue
            if t.get("status") != "CLOSED":
                continue
            if t.get("pnl", 0) >= 0:
                continue

            closed_at = t.get("closed_at", "")
            if not closed_at:
                continue

            try:
                close_dt = datetime.fromisoformat(closed_at.replace("Z", "+00:00"))
                # Handle naive timestamps (no timezone) — assume UTC
                if close_dt.tzinfo is None:
                    close_dt = close_dt.replace(tzinfo=timezone.utc)
                elapsed_hours = (now - close_dt).total_seconds() / 3600
                if elapsed_hours < SYMBOL_COOLDOWN_HOURS:
                    remaining = round(SYMBOL_COOLDOWN_HOURS - elapsed_hours, 1)
                    reason = (f"SYMBOL COOLDOWN: {symbol} lost ${abs(t.get('pnl', 0)):.2f} "
                             f"({elapsed_hours:.1f}h ago). Wait {remaining}h more. "
                             f"No revenge trading on losing pairs.")
                    self.blocked = True
                    self.block_reasons.append(reason)
                    self.score -= 10
                    return {"passed": False, "reason": reason,
                            "cooldown_remaining_h": remaining}
            except (ValueError, TypeError, OverflowError):
                continue
            break  # Only need the most recent loss

        return {"passed": True, "reason": f"{symbol} — no active cooldown"}

    def run_full_check(self, symbol: str, direction: str, entry: float,
                      sl: float, tp1: float, tp2: float = None,
                      confluences: int = 0, mirofish_result: dict = None,
                      rsi_data: dict = None, volume_data: dict = None,
                      candle_type: str = None, session: str = None,
                      high_52w: float = None, low_52w: float = None,
                      atr: float = None, week_open: float = None) -> dict:
        """Run ALL entry checks and return composite result."""

        checks = {}

        # 1. R:R check (hard gate)
        checks["risk_reward"] = self.check_risk_reward(entry, sl, tp1)

        # 2. Confluence check (hard gate)
        checks["confluences"] = self.check_confluences(confluences)

        # 3. Weekly exhaustion check (hard gate — don't chase)
        if week_open and week_open > 0:
            checks["weekly_exhaustion"] = self.check_weekly_exhaustion(
                symbol, direction, week_open, entry
            )

        # 4. Per-symbol cooldown (hard block — no revenge trading on losing pairs)
        checks["symbol_cooldown"] = self.check_symbol_cooldown(symbol)

        # 4b. Consecutive loss circuit breaker (hard block after N losses in a row)
        checks["loss_streak"] = self.check_consecutive_losses()

        # 5. Weekend hold risk check (HARD BLOCK on Friday evening)
        checks["weekend_hold"] = self.check_weekend_hold_risk()

        # 5. Max SL distance check (hard gate)
        checks["max_sl"] = self.check_max_sl_distance(symbol, entry, sl, atr)

        # 6. MiroFish contrarian check (hard gate)
        if mirofish_result:
            checks["mirofish"] = self.check_mirofish_contraind(mirofish_result)

        # 6. Regime filter (hard gate — blocks capitulation/high-vol)
        checks["regime"] = self.check_regime(symbol, entry, high_52w, low_52w, atr)

        # 7. Reversal detection (hard gate for CRITICAL, warning for HIGH)
        checks["reversal"] = self.check_reversal_risk(
            direction, rsi_data=rsi_data, volume_data=volume_data, candle_type=candle_type
        )

        # 8. Session timing (soft check)
        checks["session"] = self.check_session_timing(session)

        # Build final result
        self.score = max(0, min(10, self.score))

        if self.blocked:
            verdict = "REJECTED"
            recommendation = "DO NOT ENTER — one or more hard gates failed"
        elif self.score < 5:
            verdict = "REJECTED"
            recommendation = "Score below 5.0 — too many risk signals"
            self.blocked = True
            self.block_reasons.append(f"Composite score {self.score:.1f} < 5.0")
        elif self.warnings:
            verdict = "APPROVED_WITH_WARNINGS"
            recommendation = "Entry allowed but monitor closely — warnings present"
        else:
            verdict = "APPROVED"
            recommendation = "All gates passed — entry valid"

        result = {
            "symbol": symbol,
            "direction": direction,
            "entry": entry,
            "sl": sl,
            "tp1": tp1,
            "tp2": tp2,
            "verdict": verdict,
            "score": round(self.score, 1),
            "recommendation": recommendation,
            "checks": checks,
            "block_reasons": self.block_reasons,
            "warnings": self.warnings,
            "timestamp": datetime.now(timezone.utc).isoformat()
        }

        return result


def main():
    parser = argparse.ArgumentParser(description="Pre-Entry Validation Filter")
    parser.add_argument("--symbol", required=True)
    parser.add_argument("--direction", required=True, choices=["LONG", "SHORT"])
    parser.add_argument("--entry", required=True, type=float)
    parser.add_argument("--sl", required=True, type=float)
    parser.add_argument("--tp1", required=True, type=float)
    parser.add_argument("--tp2", type=float, default=None)
    parser.add_argument("--confluences", type=int, default=0)
    parser.add_argument("--mirofish-result", help="Path to MiroFish validation JSON")
    parser.add_argument("--candle-type", help="Current candle pattern (e.g., SHOOTING_STAR)")
    parser.add_argument("--session", help="Trading session (london, ny, asian)")
    parser.add_argument("--high-52w", type=float, help="52-week high for regime filter")
    parser.add_argument("--low-52w", type=float, help="52-week low for regime filter")
    parser.add_argument("--atr", type=float, help="14-period ATR for volatility regime")
    parser.add_argument("--week-open", type=float, help="Week opening price for exhaustion check")
    parser.add_argument("--output", help="Output JSON path")
    args = parser.parse_args()

    # Load MiroFish result if provided
    mirofish = None
    if args.mirofish_result and os.path.exists(args.mirofish_result):
        with open(args.mirofish_result) as f:
            mirofish = json.load(f)

    # Run filter
    ef = EntryFilter()
    result = ef.run_full_check(
        symbol=args.symbol,
        direction=args.direction,
        entry=args.entry,
        sl=args.sl,
        tp1=args.tp1,
        tp2=args.tp2,
        confluences=args.confluences,
        mirofish_result=mirofish,
        candle_type=args.candle_type,
        session=args.session,
        high_52w=args.high_52w,
        low_52w=args.low_52w,
        atr=args.atr,
        week_open=args.week_open
    )

    # Output
    print(json.dumps(result, indent=2))

    if args.output:
        os.makedirs(os.path.dirname(args.output), exist_ok=True)
        with open(args.output, "w") as f:
            json.dump(result, f, indent=2)
        print(f"\nSaved to {args.output}")

    # Exit code
    if result["verdict"] == "REJECTED":
        print(f"\n❌ REJECTED — Score: {result['score']}/10")
        for r in result["block_reasons"]:
            print(f"  🚫 {r}")
        sys.exit(1)
    elif result["verdict"] == "APPROVED_WITH_WARNINGS":
        print(f"\n⚠️  APPROVED WITH WARNINGS — Score: {result['score']}/10")
        for w in result["warnings"]:
            print(f"  ⚡ {w}")
        sys.exit(2)
    else:
        print(f"\n✅ APPROVED — Score: {result['score']}/10")
        sys.exit(0)


if __name__ == "__main__":
    main()
